import type { Metadata } from "next";
import "@/styles/globals.css";

// const inter = Inter({
//   subsets: ["latin", "cyrillic"],
//   weight: ["400", "500", "600", "700"],
//   display: "block",
//   variable: "--font-inter",
//   preload: true,
//   fallback: ["system-ui", "arial"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
